export const scalesListsForDictation = {
  Saba: [
    { name: "saba_dict1", notes: ["re", "sol_b", "fa", "sol_b"] },
    { name: "saba_dict2", notes: ["re", "mi_q", "sol_b", "fa"] },
    { name: "saba_dict3", notes: ["re", "fa", "mi_q", "fa"] },
    { name: "saba_dict4", notes: ["re", "mi_q", "fa", "sol_b"] },
    { name: "saba_dict5", notes: ["sol_b", "fa", "mi_q", "re"] },
    // { name: "saba_dict6", notes: ["re", "sol_b", "mi_q", "fa"] },
    // { name: "saba_dict7", notes: ["sol_b", "fa", "re", "mi_q"] },
    // { name: "saba_dict8", notes: ["re", "fa", "sol_b", "mi_q"] },
    // { name: "saba_dict9", notes: ["sol_b", "fa", "mi_q", "sol_b"] },
    // { name: "saba_dict10", notes: ["re", "sol_b", "fa", "fa"] },
    // { name: "saba_dict11", notes: ["re", "fa", "mi_q", "sol_b"] },
    // { name: "saba_dict12", notes: ["sol_b", "mi_q", "fa", "re"] },
    // { name: "saba_dict13", notes: ["sol_b", "si_b", "fa", "mi_q"] },
    // { name: "saba_dict14", notes: ["sol_b", "si_b", "fa", "re"] },
    // { name: "saba_dict15", notes: ["si_b", "sol_b", "fa", "mi_q"] },
    // { name: "saba_dict16", notes: ["re", "sol_b", "fa", "sol_b"] },
    // { name: "saba_dict17", notes: ["mi_q", "re", "sol_b", "fa"] },
    // { name: "saba_dict18", notes: ["re", "mi_q", "fa", "sol_b"] },
    // { name: "saba_dict19", notes: ["sol_b", "fa", "mi_q", "re"] },
  ],
  Nahawand: [
    { name: "nahawand_dict1", notes: ["do", "re", "mi_b", "fa"] },
    { name: "nahawand_dict2", notes: ["fa", "mi_b", "re", "do"] },
    { name: "nahawand_dict3", notes: ["do", "mi_b", "sol", "do"] },
    { name: "nahawand_dict4", notes: ["do", "mi_b", "fa", "do"] },
    { name: "nahawand_dict5", notes: ["sol", "la_b", "fa", "mi_b"] },
    // { name: "nahawand_dict6", notes: ["sol", "la_b", "fa", "sol"] },
    // { name: "nahawand_dict7", notes: ["sol", "la_b", "fa", "re"] },
    // { name: "nahawand_dict8", notes: ["re", "mi_b", "re", "do"] },
    // { name: "nahawand_dict9", notes: ["sol", "fa", "mi_b", "fa"] },
    // { name: "nahawand_dict10", notes: ["si", "la_b", "sol", "do"] },
    // { name: "nahawand_dict11", notes: ["do", "re", "mi_b", "re"] },
    // { name: "nahawand_dict12", notes: ["do", "re", "mi_b", "do"] },
  ],
  Agam: [
    { name: "agam_dict1", notes: ["do", "re", "mi", "fa"] },
    { name: "agam_dict2", notes: ["fa", "mi", "re", "do"] },
    { name: "agam_dict3", notes: ["do", "mi", "sol", "do"] },
    { name: "agam_dict4", notes: ["do", "mi", "fa", "do"] },
    { name: "agam_dict5", notes: ["sol", "la", "fa", "mi"] },
    // { name: "agam_dict6", notes: ["sol", "la", "fa", "sol"] },
    // { name: "agam_dict7", notes: ["sol", "la", "fa", "re"] },
    // { name: "agam_dict8", notes: ["re", "mi", "re", "do"] },
    // { name: "agam_dict9", notes: ["sol", "fa", "mi", "fa"] },
    // { name: "agam_dict10", notes: ["si", "la", "sol", "do"] },
    // { name: "agam_dict11", notes: ["do", "re", "mi", "re"] },
    // { name: "agam_dict12", notes: ["do", "re", "mi", "do"] },
  ],
  Bayaty: [
    { name: "bayaty_dict1", notes: ["re", "sol", "fa", "mi_q"] },
    { name: "bayaty_dict2", notes: ["re", "sol", "fa", "sol"] },
    { name: "bayaty_dict3", notes: ["fa", "mi_q", "re", "mi_q"] },
    { name: "bayaty_dict4", notes: ["re", "mi_q", "fa", "re"] },
    { name: "bayaty_dict5", notes: ["re", "sol", "mi_q", "re"] },
    // { name: "bayaty_dict6", notes: ["sol", "la", "mi_q", "re"] },
    // { name: "bayaty_dict7", notes: ["fa", "sol", "mi_q", "re"] },
    // { name: "bayaty_dict8", notes: ["sol", "si_b", "mi_q", "re"] },
    // { name: "bayaty_dict9", notes: ["sol", "si_b", "fa", "mi_q"] },
    // { name: "bayaty_dict10", notes: ["re", "mi_q", "fa", "mi_q"] },
    // { name: "bayaty_dict11", notes: ["mi_q", "fa", "mi_q", "re"] },
    // { name: "bayaty_dict12", notes: ["sol", "fa", "mi_q", "re"] },
    // { name: "bayaty_dict13", notes: ["re", "fa", "mi_q", "re"] },
    // { name: "bayaty_dict17", notes: ["re", "mi_q", "fa", "sol"] },
  ],
  Sika: [
    { name: "sika_dict1", notes: ["mi_q", "fa", "sol", "fa"] },
    { name: "sika_dict2", notes: ["mi_q", "fa", "mi_q", "mi_q"] },
    { name: "sika_dict3", notes: ["fa", "sol", "fa", "mi_q"] },
    { name: "sika_dict4", notes: ["fa", "sol", "la", "si_q"] },
    { name: "sika_dict5", notes: ["mi_q", "fa", "la", "mi_q"] },
    // { name: "sika_dict6", notes: ["mi_q", "fa", "mi_q", "sol"] },
    // { name: "sika_dict7", notes: ["mi_q", "fa", "la", "sol"] },
    // { name: "sika_dict8", notes: ["mi_q", "fa", "fa", "sol"] },
    // { name: "sika_dict9", notes: ["mi_q", "la", "sol", "fa"] },
    // { name: "sika_dict11", notes: ["mi_q", "sol", "la", "si_q"] },
    // { name: "sika_dict12", notes: ["si_q", "la", "si_q", "sol"] },
    // { name: "sika_dict13", notes: ["si_q", "la", "fa", "sol"] },
    // { name: "sika_dict14", notes: ["si_q", "la", "mi_q", "fa"] },
    // { name: "sika_dict15", notes: ["si_q", "la", "fa", "mi_q"] },
  ],
  Hegaz: [
    { name: "hegaz_dict1", notes: ["re", "mi_b", "fa_d", "sol"] },
    { name: "hegaz_dict2", notes: ["re", "sol", "fa_d", "mi_b"] },
    { name: "hegaz_dict3", notes: ["sol", "fa_d", "sol", "mi_b"] },
    { name: "hegaz_dict4", notes: ["fa_d", "mi_b", "fa_d", "re"] },
    { name: "hegaz_dict5", notes: ["re", "sol", "fa_d", "re"] },
    // { name: "hegaz_dict6", notes: ["re", "mi_b", "fa_d", "mi_b"] },
    // { name: "hegaz_dict7", notes: ["sol", "fa_d", "sol", "la"] },
    // { name: "hegaz_dict8", notes: ["sol", "fa_d", "mi_b", "re"] },
    // { name: "hegaz_dict9", notes: ["sol", "la", "mi_b", "sol"] },
    // { name: "hegaz_dict10", notes: ["sol", "la", "mi_b", "re"] },
    // { name: "hegaz_dict11", notes: ["si_b", "la", "fa_d", "mi_b"] },
    // { name: "hegaz_dict12", notes: ["si_b", "la", "mi_b", "fa_d"] },
    // { name: "hegaz_dict13", notes: ["la", "si_b", "fa_d", "mi_b"] },
    // { name: "hegaz_dict14", notes: ["si_b", "la", "mi_b", "re"] },
    // { name: "hegaz_dict15", notes: ["sol", "fa_d", "sol", "re"] },
    // { name: "hegaz_dict16", notes: ["sol", "fa_d", "sol", "mi_b"] },
    // { name: "hegaz_dict17", notes: ["fa_d", "sol", "la", "fa_d"] },
    // { name: "hegaz_dict18", notes: ["fa_d", "sol", "mi_b", "fa_d"] },
    // { name: "hegaz_dict19", notes: ["fa_d", "mi_b", "fa_d", "fa_d"] },
    // { name: "hegaz_dict20", notes: ["re", "mi_b", "mi_b", "fa_d"] },
    // { name: "hegaz_dict21", notes: ["si_b", "la", "si_b", "fa_d"] },
    // { name: "hegaz_dict22", notes: ["mi_b", "fa_d", "re", "mi_b"] },
    // { name: "hegaz_dict23", notes: ["sol", "fa_d", "re", "re"] },
  ],
  Rast: [
    { name: "rast_dict1", notes: ["do", "re", "mi_q", "fa"] },
    { name: "rast_dict2", notes: ["fa", "mi_q", "re", "do"] },
    { name: "rast_dict3", notes: ["do", "mi_q", "fa", "sol"] },
    { name: "rast_dict4", notes: ["do", "re", "fa", "sol"] },
    { name: "rast_dict5", notes: ["do", "mi_q", "sol", "do"] },
    // { name: "rast_dict6", notes: ["do", "re", "fa", "si_q"] },
    // { name: "rast_dict7", notes: ["do", "mi_q", "sol", "la"] },
    // { name: "rast_dict8", notes: ["si_q", "la", "sol", "la"] },
    // { name: "rast_dict9", notes: ["si_q", "la", "sol", "si_q"] },
    // { name: "rast_dict10", notes: ["si_q", "do", "si_q", "la"] },
    // { name: "rast_dict11", notes: ["la", "sol", "fa", "mi_q"] },
    // { name: "rast_dict12", notes: ["sol", "fa", "mi_q", "re"] },
    // { name: "rast_dict13", notes: ["fa", "mi_q", "re", "do"] },
  ],
  Kurd: [
    { name: "kurd_dict1", notes: ["re", "sol", "fa", "mi_b"] },
    { name: "kurd_dict2", notes: ["re", "sol", "fa", "sol"] },
    { name: "kurd_dict3", notes: ["fa", "mi_b", "re", "mi_b"] },
    { name: "kurd_dict4", notes: ["re", "mi_b", "fa", "re"] },
    { name: "kurd_dict5", notes: ["re", "sol", "mi_b", "re"] },
    // { name: "kurd_dict6", notes: ["sol", "la", "mi_b", "re"] },
    // { name: "kurd_dict7", notes: ["fa", "sol", "mi_b", "re"] },
    // { name: "kurd_dict8", notes: ["sol", "si_b", "mi_b", "re"] },
    // { name: "kurd_dict9", notes: ["sol", "si_b", "fa", "mi_b"] },
    // { name: "kurd_dict10", notes: ["re", "mi_b", "fa", "mi_b"] },
    // { name: "kurd_dict11", notes: ["mi_b", "fa", "mi_b", "re"] },
    // { name: "kurd_dict12", notes: ["sol", "fa", "mi_b", "re"] },
    // { name: "kurd_dict13", notes: ["re", "fa", "mi_b", "re"] },
    // { name: "kurd_dict14", notes: ["re", "mi_b", "fa", "sol"] },
  ],
};
